

@host = <RESOURCE_NAME>.azure-api.net
@port = 443
@subscriptionKey = <APIM_SUBSCRIPTION_KEY>

GET https://{{host}}:{{port}}/mcp/sse
Content-Type: application/json
Ocp-Apim-Subscription-Key: "{{subscriptionKey}}"

